// Central catalogue for the BINDY — Serendipity collection.
// One shared source of truth for the shop grid, quick-view modal and product pages.

export type Category =
  | "Dresses"
  | "Tops & Blouses"
  | "Skirts & Pants"
  | "Two Piece Sets";

export type Destination = "Beach" | "Party" | "City" | "Garden" | "Everyday";

export interface Review {
  id: string;
  productId: string;
  reviewerName: string;
  reviewerLocation: string; // e.g. "Brisbane, QLD"
  rating: 1 | 2 | 3 | 4 | 5;
  title: string;
  body: string;
  date: string; // ISO format, must be a real past date (not future-dated)
  verified: boolean;
  helpfulCount: number;
  fit: "small" | "true" | "large";
  photos?: string[]; // optional customer photo URLs, leave empty array if none
}

export interface Product {
  id: string; // also used as the URL slug
  name: string;
  category: Category;
  story: string; // the poetic collection chapter name
  storyPlace: string; // the heritage place it draws from
  destinations: Destination[];
  colorName: string;
  colorHex: string;
  palette: string[]; // supporting swatch hexes
  fabric: string;
  priceAud: number;
  image: string; // primary
  imageHover: string; // shown on card hover
  videoHover?: string; // optional short clip played on card hover (falls back to imageHover)
  gallery: string[]; // full gallery for the product page (incl. image + hover)
  sizes: string[];
  description: string; // short card / modal blurb
  heritage: string; // long narrative for the product page
  quote: string; // one poetic line from the concept board
  craftDetails: string[];
  care: string[];
  reviews: Review[];
}

const AU_SIZES = ["AU 6 (XS)", "AU 8 (S)", "AU 10 (M)", "AU 12 (L)", "AU 14 (XL)"];

export const PRODUCTS: Product[] = [
  {
    id: "lotus-memory-dress",
    name: "Lotus Memory Strapless Dress",
    category: "Dresses",
    story: "Fragment of Memories",
    storyPlace: "The Lotus Ponds of Sri Lanka",
    destinations: ["Garden", "Everyday"],
    colorName: "Lotus Pink",
    colorHex: "#E8B7C3",
    palette: ["#E8B7C3", "#F6F5F2", "#DCC7AF"],
    fabric: "Lightweight Cotton Voile",
    priceAud: 240,
    image: "/images/serendipity/lotus-memory-dress.jpg",
    imageHover: "/images/serendipity/lotus-memory-dress-hover.jpg",
    videoHover: "/videos/serendipity/lotus-memory-dress-hover.mp4",
    gallery: [
      "/images/serendipity/lotus-memory-dress.jpg",
      "/images/serendipity/lotus-memory-dress-hover.jpg",
      "/images/serendipity/lotus-memory-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by Sri Lankan lotus ponds. A structured bodice reflecting inner strength, softened by a gathered skirt that unfolds like petals.",
    heritage:
      "Inspired by the still lotus ponds of Sri Lanka, where every memory blooms in its own time. The structured bodice mirrors quiet inner strength, while the softly gathered skirt opens like petals reaching for the morning sun — a piece made to be worn slowly, and remembered.",
    quote: "Every memory blooms in its own time.",
    craftDetails: [
      "Princess seams for a sculpted bodice",
      "Soft petal gathers through the skirt",
      "Concealed side zipper",
      "Fully lined for opacity",
    ],
    care: ["Gentle cold machine wash", "Line dry in shade", "Warm iron on reverse"],
    reviews: [
      {
        id: "lm-rev-1",
        productId: "lotus-memory-dress",
        reviewerName: "Amara P.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Feels like a quiet memory",
        body: "The lightweight cotton voile is so featherlight I forget I'm wearing it. Wore it to a botanical garden lunch in New Farm and three people asked where it was from. The petal gathering falls effortlessly.",
        date: "2026-07-14",
        verified: true,
        helpfulCount: 24,
        fit: "true",
        photos: ["/images/serendipity/lotus-memory-dress.jpg"],
      },
      {
        id: "lm-rev-2",
        productId: "lotus-memory-dress",
        reviewerName: "Chloe M.",
        reviewerLocation: "Gold Coast, QLD",
        rating: 5,
        title: "That gathered skirt is pure poetry",
        body: "The movement is unreal. True to size, the AU 8 fits my frame beautifully without slipping down at the bust line. Perfect for balmy Queensland evenings by the water.",
        date: "2026-06-02",
        verified: true,
        helpfulCount: 18,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-3",
        productId: "lotus-memory-dress",
        reviewerName: "Elena Vasquez",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Incredible artisan finish",
        body: "You can truly tell this is slow fashion. The internal structuring is supportive yet soft, and the lotus pink hue has this subtle warmth under natural Australian sunlight.",
        date: "2026-05-18",
        verified: true,
        helpfulCount: 12,
        fit: "true",
        photos: ["/images/serendipity/lotus-memory-dress-hover.jpg"],
      },
      {
        id: "lm-rev-4",
        productId: "lotus-memory-dress",
        reviewerName: "Siobhan K.",
        reviewerLocation: "Sydney, NSW",
        rating: 4,
        title: "Sublime fabric, slightly snug across the bust",
        body: "I am between an AU 10 and 12 and opted for the 10. It fits like a glove around the waist but is slightly firm across the bust. I recommend sizing up if you have a larger cup size.",
        date: "2026-04-11",
        verified: true,
        helpfulCount: 9,
        fit: "small",
        photos: [],
      },
      {
        id: "lm-rev-5",
        productId: "lotus-memory-dress",
        reviewerName: "Zara Wickramasinghe",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Connecting both of my worlds",
        body: "Growing up between Colombo and Fremantle, wearing a dress that celebrates Ceylon lotus ponds in such an elevated, minimal silhouette brought a genuine smile to my face. Beautifully crafted.",
        date: "2026-03-24",
        verified: true,
        helpfulCount: 31,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-6",
        productId: "lotus-memory-dress",
        reviewerName: "Sophie Lin",
        reviewerLocation: "Adelaide, SA",
        rating: 4,
        title: "Effortless elegance for a Barossa winery afternoon",
        body: "Wore this for a weekend in the Barossa Valley. Paired with flat leather sandals and an unbuttoned linen overshirt. Only note is that it requires gentle steaming after suitcase travel.",
        date: "2026-02-09",
        verified: true,
        helpfulCount: 5,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-7",
        productId: "lotus-memory-dress",
        reviewerName: "Hannah De Silva",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Drapes like a dream",
        body: "The cotton lining is completely opaque and so soft against the skin. Great length on my 168cm frame. Washed gently on cold cycle and it kept its texture beautifully.",
        date: "2025-12-19",
        verified: false,
        helpfulCount: 7,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-8",
        productId: "lotus-memory-dress",
        reviewerName: "Lucinda Grey",
        reviewerLocation: "Byron Bay, NSW",
        rating: 3,
        title: "Gorgeous piece, wished it had hidden pockets",
        body: "The cotton voile and bodice craftsmanship are 5-star quality without question. I only gave 3 stars because I really wish a casual strapless summer dress at this price point included concealed side pockets.",
        date: "2025-10-30",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "serendib-pearl-dress",
    name: "The Island Pearl Maxi Dress",
    category: "Dresses",
    story: "The Serendib Pearl",
    storyPlace: "The Coastal Waters of Serendib",
    destinations: ["Beach", "Party"],
    colorName: "Ivory White",
    colorHex: "#F6F5F2",
    palette: ["#F6F5F2", "#DCC7AF", "#C8D8E6"],
    fabric: "Pure Cotton with Cutwork Lace",
    priceAud: 285,
    image: "/images/serendipity/serendib-pearl-dress.jpg",
    imageHover: "/images/serendipity/serendib-pearl-dress-hover.jpg",
    videoHover: "/videos/serendipity/serendib-pearl-dress-hover.mp4",
    gallery: [
      "/images/serendipity/serendib-pearl-dress.jpg",
      "/images/serendipity/serendib-pearl-dress-hover.jpg",
      "/images/serendipity/serendib-pearl-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "A celebration of coastal pearl lustre. Hand-cut lace along the neckline and a sweeping cutwork scallop hem.",
    heritage:
      "Hidden beneath the waters of Serendib, the pearl waits — an unexpected treasure revealed only by quiet beauty. Cutwork lace and a gently gathered waist echo shell texture and the slow movement of the ocean, carrying that lustre from the shore into your wardrobe.",
    quote: "Hidden beneath the water, an unexpected treasure of quiet beauty.",
    craftDetails: [
      "Hand-cut cutwork lace neckline",
      "Gathered empire waist",
      "Scalloped cutwork hem",
      "Adjustable back tie",
    ],
    care: ["Hand wash cold", "Do not bleach", "Cool iron lace on reverse"],
    reviews: [
      {
        id: "sp-rev-1",
        productId: "serendib-pearl-dress",
        reviewerName: "Isabelle R.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Wore it to a coastal wedding at Wategos",
        body: "Photographs like an absolute dream and stayed completely breathable in 28-degree coastal humidity. The hand-cut cutwork lace is heirloom quality — not mass produced in the slightest.",
        date: "2026-07-20",
        verified: true,
        helpfulCount: 42,
        fit: "true",
        photos: ["/images/serendipity/serendib-pearl-dress.jpg"],
      },
      {
        id: "sp-rev-2",
        productId: "serendib-pearl-dress",
        reviewerName: "Priya S.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Serene, luminous ivory cotton",
        body: "The tone is a soft, natural ivory rather than a clinical stark white. The scallop hem skims just above the floor when barefoot. Completely enamored with the details.",
        date: "2026-06-15",
        verified: true,
        helpfulCount: 20,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-3",
        productId: "serendib-pearl-dress",
        reviewerName: "Charlotte Vance",
        reviewerLocation: "Noosa, QLD",
        rating: 5,
        title: "The back tie detail is perfection",
        body: "Allows you to adjust the fit through the bust and ribcage exactly as you want. I wore it for our beachfront anniversary dinner and felt so poised and relaxed.",
        date: "2026-05-04",
        verified: true,
        helpfulCount: 15,
        fit: "true",
        photos: ["/images/serendipity/serendib-pearl-dress-hover.jpg"],
      },
      {
        id: "sp-rev-4",
        productId: "serendib-pearl-dress",
        reviewerName: "Maya Perera",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Slightly generous length for petite frames",
        body: "The dress is magnificent. I am 160cm so I had it taken up 2 inches at the local tailor, but the cutwork scallop detail remained intact. Worth every cent.",
        date: "2026-04-02",
        verified: true,
        helpfulCount: 11,
        fit: "large",
        photos: [],
      },
      {
        id: "sp-rev-5",
        productId: "serendib-pearl-dress",
        reviewerName: "Harriet Cole",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Heirloom piece to keep forever",
        body: "You feel the artisan hands in every single stitch of cutwork. A timeless summer staple that outlasts transient fast-fashion trends.",
        date: "2026-02-18",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-6",
        productId: "serendib-pearl-dress",
        reviewerName: "Gemma Thorne",
        reviewerLocation: "Cairns, QLD",
        rating: 5,
        title: "Breathable tropical luxury",
        body: "Pure cotton that lets the ocean breeze flow right through. The lace on the neckline frames the collarbones exquisitely.",
        date: "2025-11-28",
        verified: false,
        helpfulCount: 4,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-7",
        productId: "serendib-pearl-dress",
        reviewerName: "Annabelle Scott",
        reviewerLocation: "Brisbane, QLD",
        rating: 4,
        title: "Pure elegance, lace needs delicate care",
        body: "The craftsmanship is remarkable. Just be mindful when washing — strictly hand-wash cold to preserve the intricate cutwork edges.",
        date: "2025-09-14",
        verified: true,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "pettah-check-dress",
    name: "A Pettah Discovery A-Line Dress",
    category: "Dresses",
    story: "A Pettah Discovery",
    storyPlace: "The Red Mosque, Pettah",
    destinations: ["City", "Everyday"],
    colorName: "Crimson Check",
    colorHex: "#A82B35",
    palette: ["#A82B35", "#F6F5F2", "#AFC8B1"],
    fabric: "Handwoven Cotton Gingham",
    priceAud: 220,
    image: "/images/serendipity/pettah-check-dress.jpg",
    imageHover: "/images/serendipity/pettah-check-dress-hover.jpg",
    videoHover: "/videos/serendipity/pettah-check-dress-hover.mp4",
    gallery: [
      "/images/serendipity/pettah-check-dress.jpg",
      "/images/serendipity/pettah-check-dress-hover.jpg",
      "/images/serendipity/pettah-check-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by Colombo's candy-striped Red Mosque. An architectural notched collar and tailored button rhythm.",
    heritage:
      "Among Pettah's restless streets stands the candy-striped Jumma Mosque, its red-and-white arches unmistakable against the noise. That rhythm of pattern, contrast and architecture shapes this notched-collar, A-line dress — a quiet discovery carried out of the old city.",
    quote: "Among Pettah's restless streets, an unexpected pattern stops you.",
    craftDetails: [
      "Notched lapel collar",
      "Covered button front placket",
      "A-line silhouette with waist seam",
      "Handwoven gingham, yarn-dyed",
    ],
    care: ["Cold machine wash", "Line dry", "Warm iron"],
    reviews: [
      {
        id: "pc-rev-1",
        productId: "pettah-check-dress",
        reviewerName: "Georgia T.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Flattering, architectural cut",
        body: "The notched collar and covered button placket give it such a chic tailored feel without losing the relaxed comfort of handloom cotton. Wear it to my design studio and on weekend gallery walks.",
        date: "2026-06-25",
        verified: true,
        helpfulCount: 29,
        fit: "true",
        photos: ["/images/serendipity/pettah-check-dress.jpg"],
      },
      {
        id: "pc-rev-2",
        productId: "pettah-check-dress",
        reviewerName: "Hannah W.",
        reviewerLocation: "Adelaide, SA",
        rating: 5,
        title: "Everyday favourite for city & market days",
        body: "Bought it for work, now I find myself reaching for it every Saturday morning. The handwoven gingham has substantial weight while remaining crisp and airy.",
        date: "2026-05-12",
        verified: true,
        helpfulCount: 16,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-3",
        productId: "pettah-check-dress",
        reviewerName: "Natasha Mendis",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "The Red Mosque inspiration is spot on",
        body: "Such a clever homage to Colombo heritage. The crimson tone is vibrant yet sophisticated, not overwhelming. AU 10 fits true to size.",
        date: "2026-04-19",
        verified: true,
        helpfulCount: 22,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-4",
        productId: "pettah-check-dress",
        reviewerName: "Tegan Brooks",
        reviewerLocation: "Canberra, ACT",
        rating: 4,
        title: "Smart and structured for the office",
        body: "Holds its shape throughout an 8-hour workday. The waist seam hits at the most flattering point. Very pleased with the quality.",
        date: "2026-03-08",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-5",
        productId: "pettah-check-dress",
        reviewerName: "Clara Bennett",
        reviewerLocation: "Gold Coast, QLD",
        rating: 4,
        title: "Love the covered buttons and lapel",
        body: "Deeply impressed with the finish. The covered buttons are a gorgeous artisan touch. Fabric feels durable and natural.",
        date: "2026-01-14",
        verified: true,
        helpfulCount: 3,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-6",
        productId: "pettah-check-dress",
        reviewerName: "Anouk Senanayake",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Wore it straight off the plane",
        body: "Travels exceptionally well. Ironed with light steam and it looked brand new immediately. High rotation in my wardrobe.",
        date: "2025-11-20",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "ocean-embraced-tiered-dress",
    name: "Embraced By Blue Tiered Maxi",
    category: "Dresses",
    story: "Embraced by Blue",
    storyPlace: "Where the Island Meets the Ocean",
    destinations: ["Beach", "Everyday"],
    colorName: "Washed Sea Blue",
    colorHex: "#2F4F6F",
    palette: ["#2F4F6F", "#C8D8E6", "#F6F5F2"],
    fabric: "Chambray Weave Cotton",
    priceAud: 260,
    image: "/images/serendipity/ocean-embraced-tiered-dress.jpg",
    imageHover: "/images/serendipity/ocean-embraced-tiered-dress-hover.jpg",
    videoHover: "/videos/serendipity/ocean-embraced-tiered-dress-hover.mp4",
    gallery: [
      "/images/serendipity/ocean-embraced-tiered-dress.jpg",
      "/images/serendipity/ocean-embraced-tiered-dress-hover.jpg",
      "/images/serendipity/ocean-embraced-tiered-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Where the island meets the sea. Soft washed chambray woven in gathered wave tiers for sun-drenched days.",
    heritage:
      "When the island meets the ocean, an endless blue journey quietly begins. Washed chambray falls in gathered wave tiers — freedom, movement and calm woven into a maxi made for long, sun-drenched Australian days by the water.",
    quote: "When the island cries, an endless blue journey quietly begins.",
    craftDetails: [
      "Gathered wave tiers",
      "Shell button placket",
      "Relaxed coastal drape",
      "Breathable chambray weave",
    ],
    care: ["Cold machine wash", "Line dry in shade", "Warm iron"],
    reviews: [
      {
        id: "ob-rev-1",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Maddie L.",
        reviewerLocation: "Sunshine Coast, QLD",
        rating: 5,
        title: "My quintessential coastal uniform",
        body: "The tiers move like ocean waves in the sea breeze. Genuinely cool to wear during 32-degree coastal heatwaves. The genuine shell buttons catch the morning sunlight subtly.",
        date: "2026-07-08",
        verified: true,
        helpfulCount: 38,
        fit: "true",
        photos: ["/images/serendipity/ocean-embraced-tiered-dress.jpg"],
      },
      {
        id: "ob-rev-2",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Sana K.",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "That deep washed indigo hue",
        body: "The washed sea blue colour is even richer in person. Roomy and ultra comfortable without looking shapeless. AU 10 fits true to size.",
        date: "2026-06-01",
        verified: true,
        helpfulCount: 19,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-3",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Ailsa MacLeod",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "From Bondi morning coffee to sunset drinks",
        body: "Throws on effortlessly over swimwear with sandals, or dresses up with gold statement earrings for evening cocktails. The chambray softens with every wash.",
        date: "2026-04-27",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-4",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Kavitha R.",
        reviewerLocation: "Darwin, NT",
        rating: 5,
        title: "Survives tropical humidity effortlessly",
        body: "Living up north, finding dresses that truly breathe is essential. This chambray weave is a lifesaver. Pure comfort from dawn till dusk.",
        date: "2026-03-15",
        verified: true,
        helpfulCount: 9,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-5",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Lucy Sterling",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Generous flow, consider sizing down if between sizes",
        body: "Beautiful relaxed cut. If you prefer a closer fit across the chest and shoulders you could consider sizing down, but I adore the breezy silhouette.",
        date: "2026-02-02",
        verified: true,
        helpfulCount: 12,
        fit: "large",
        photos: [],
      },
      {
        id: "ob-rev-6",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Bridie O'Connor",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Coastal perfection with weighted hem",
        body: "The craft and hem weight are second to none. It billows gracefully in the ocean wind rather than flying up wildly.",
        date: "2025-11-10",
        verified: false,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "shore-traces-blouse",
    name: "Traces in the Sand Peplum Top",
    category: "Tops & Blouses",
    story: "Traces in the Sand",
    storyPlace: "The Sri Lankan Shore",
    destinations: ["Beach", "City"],
    colorName: "Sand Beige Check",
    colorHex: "#DCC7AF",
    palette: ["#DCC7AF", "#F6F5F2", "#A46446"],
    fabric: "Fine Handloom Cotton",
    priceAud: 175,
    image: "/images/serendipity/shore-traces-blouse.jpg",
    imageHover: "/images/serendipity/shore-traces-blouse-hover.jpg",
    videoHover: "/videos/serendipity/shore-traces-blouse-hover.mp4",
    gallery: [
      "/images/serendipity/shore-traces-blouse.jpg",
      "/images/serendipity/shore-traces-blouse-hover.jpg",
      "/images/serendipity/shore-traces-blouse-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Tidal ripple motifs and soft sand checks, shaped with a peplum hem and corsetry-inspired seams.",
    heritage:
      "With every returning tide, the sand reveals a pattern never seen before. Shoreline lines and tidal ripples shape this peplum of fine sand-check handloom — structured yet soft, a trace of the shore you can carry into the city.",
    quote: "With every returning tide, the sand reveals a pattern never seen before.",
    craftDetails: [
      "Shaped peplum hem",
      "Fine woven sand check",
      "Adjustable rear ties",
      "Structural corsetry seams",
    ],
    care: ["Hand wash cold", "Line dry", "Cool iron"],
    reviews: [
      {
        id: "st-rev-1",
        productId: "shore-traces-blouse",
        reviewerName: "Ella F.",
        reviewerLocation: "Newcastle, NSW",
        rating: 5,
        title: "Sculptural yet supremely comfortable",
        body: "The corsetry-inspired seams give definition without any pinching or rigid wire. The peplum flare sits perfectly over high-waist tailored linen trousers.",
        date: "2026-06-18",
        verified: true,
        helpfulCount: 27,
        fit: "true",
        photos: ["/images/serendipity/shore-traces-blouse.jpg"],
      },
      {
        id: "st-rev-2",
        productId: "shore-traces-blouse",
        reviewerName: "Ruwani J.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Unrivalled handloom texture",
        body: "You can feel the artisan weave between your fingers. It holds crisp structure while remaining soft. The rear tie lets you cinch to your exact waistline.",
        date: "2026-05-23",
        verified: true,
        helpfulCount: 18,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-3",
        productId: "shore-traces-blouse",
        reviewerName: "Miriam Al-Hassan",
        reviewerLocation: "Sydney, NSW",
        rating: 4,
        title: "Exquisite details, back tie takes a moment",
        body: "Once you adjust the rear ties it fits like custom tailoring. The sand check is such a soothing, warm neutral that pairs with everything.",
        date: "2026-03-30",
        verified: true,
        helpfulCount: 10,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-4",
        productId: "shore-traces-blouse",
        reviewerName: "Penelope Cross",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Elevates any simple trouser or skirt",
        body: "Instantly makes any outfit look styled and considered. Received so many compliments during a corporate lunch in the city.",
        date: "2026-02-14",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-5",
        productId: "shore-traces-blouse",
        reviewerName: "Tahnee Miller",
        reviewerLocation: "Adelaide, SA",
        rating: 4,
        title: "Wore it to an afternoon tea",
        body: "Felt so refined. The peplum proportion is modern and fresh. Handloom weave breathes well in warm rooms.",
        date: "2025-12-05",
        verified: true,
        helpfulCount: 4,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-6",
        productId: "shore-traces-blouse",
        reviewerName: "Belinda Harris",
        reviewerLocation: "Perth, WA",
        rating: 3,
        title: "Careful if you have a broader back",
        body: "The peplum top is stunning in construction. I found it slightly snug across the upper back when reaching forward, so consider sizing up if you are broad-shouldered.",
        date: "2025-10-18",
        verified: true,
        helpfulCount: 11,
        fit: "small",
        photos: [],
      },
    ],
  },
  {
    id: "cinnamon-flow-skirt",
    name: "Cinnamon Flow Bias Maxi Skirt",
    category: "Skirts & Pants",
    story: "Cinnamon Flow",
    storyPlace: "The Ceylon Cinnamon Gardens",
    destinations: ["Party", "City"],
    colorName: "Cinnamon Satin",
    colorHex: "#A46446",
    palette: ["#A46446", "#F6F5F2", "#DCC7AF"],
    fabric: "Recycled Silk & Lyocell Blend",
    priceAud: 195,
    image: "/images/serendipity/cinnamon-flow-skirt.jpg",
    imageHover: "/images/serendipity/cinnamon-flow-skirt-hover.jpg",
    videoHover: "/videos/serendipity/cinnamon-flow-skirt-hover.mp4",
    gallery: [
      "/images/serendipity/cinnamon-flow-skirt.jpg",
      "/images/serendipity/cinnamon-flow-skirt-hover.jpg",
      "/images/serendipity/cinnamon-flow-skirt-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Rich cinnamon spice with earthy undertones, draped in a fluid bias cut for maximum grace.",
    heritage:
      "Drawn from the bark of Ceylon cinnamon — warm, grounding and quietly luxurious. A fluid bias cut lets the spice-brown silk move like poured honey, catching the light with every step from dinner to the dance floor.",
    quote: "Warm, grounding, and quietly luxurious.",
    craftDetails: [
      "Bias-cut fluid drape",
      "Elasticated internal waistband",
      "French seams throughout",
      "Recycled silk blend",
    ],
    care: ["Dry clean, or gentle hand wash cold", "Line dry flat", "Cool iron"],
    reviews: [
      {
        id: "cf-rev-1",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Tara D.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Moves like poured liquid amber",
        body: "The bias cut on this skirt is masterfully drafted. It glides across the hips without clinging or bunching. Wore it to an evening dinner by Sydney harbour and caught the amber sunset reflections.",
        date: "2026-07-02",
        verified: true,
        helpfulCount: 34,
        fit: "true",
        photos: ["/images/serendipity/cinnamon-flow-skirt.jpg"],
      },
      {
        id: "cf-rev-2",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Nadia H.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Effortlessly elegant & comfortable all evening",
        body: "The secret elasticated inner waistband is a triumph — looks completely seamless from the exterior but provides total ease during a multi-course dinner.",
        date: "2026-05-28",
        verified: true,
        helpfulCount: 21,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-3",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Victoria Sterling",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "French seams and luxury weighting",
        body: "The quality of craftsmanship inside is as stunning as the outside. French seams everywhere. The cinnamon hue pairs wonderfully with cream knits or black camisoles.",
        date: "2026-04-15",
        verified: true,
        helpfulCount: 16,
        fit: "true",
        photos: ["/images/serendipity/cinnamon-flow-skirt-hover.jpg"],
      },
      {
        id: "cf-rev-4",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Danielle Cox",
        reviewerLocation: "Gold Coast, QLD",
        rating: 4,
        title: "Sensational silk-blend hand feel",
        body: "Silky and soft. The length hits right above the ankle bone on me (172cm). Hand-washed in cool water and it retained its sheen perfectly.",
        date: "2026-03-11",
        verified: true,
        helpfulCount: 11,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-5",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Ashwini Jayatilleke",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Ceylon spice at its most refined",
        body: "Deep, earthy, glowing cinnamon. You cannot find this unique shade in fast-fashion chain stores. Absolutely sublime piece.",
        date: "2026-02-04",
        verified: true,
        helpfulCount: 25,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-6",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Keira Walsh",
        reviewerLocation: "Canberra, ACT",
        rating: 4,
        title: "Stunning skirt, slightly relaxed waist",
        body: "Very flattering line. I sized down to AU 8 for a firmer fit around the high waist and it sat impeccably.",
        date: "2025-11-19",
        verified: false,
        helpfulCount: 5,
        fit: "large",
        photos: [],
      },
    ],
  },
  {
    id: "celestial-terracotta-skirt",
    name: "Celestial Bloom Pleated Maxi",
    category: "Skirts & Pants",
    story: "Celestial Bloom",
    storyPlace: "The Sigiriya Frescoes",
    destinations: ["Party", "Garden"],
    colorName: "Sigiriya Terracotta",
    colorHex: "#B86B4B",
    palette: ["#B86B4B", "#F6F5F2", "#DCC7AF"],
    fabric: "Crinkle Linen & Cotton",
    priceAud: 210,
    image: "/images/serendipity/celestial-terracotta-skirt.jpg",
    imageHover: "/images/serendipity/celestial-terracotta-skirt-hover.jpg",
    videoHover: "/videos/serendipity/celestial-terracotta-skirt-hover.mp4",
    gallery: [
      "/images/serendipity/celestial-terracotta-skirt.jpg",
      "/images/serendipity/celestial-terracotta-skirt-hover.jpg",
      "/images/serendipity/celestial-terracotta-skirt-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by the ancient Sigiriya frescoes. Rich terracotta hues with subtle pleated movement.",
    heritage:
      "Painted on an ancient rock wall, the maidens of Sigiriya still bloom after fifteen centuries. Terracotta hues and softly pleated movement carry their timeless grace forward into a maxi that feels both grounded and quietly celestial.",
    quote: "From an ancient painted wall, a timeless grace quietly reappears.",
    craftDetails: [
      "Gathered waistband",
      "Breathable crinkle finish",
      "Deep concealed side pockets",
      "Fluid pleated fall",
    ],
    care: ["Cold machine wash", "Line dry to keep crinkle", "No iron needed"],
    reviews: [
      {
        id: "cb-rev-1",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Bianca N.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Deep, functional pockets in a couture skirt!",
        body: "Finding genuine, generous pockets hidden within delicate pleats is a dream come true. The Sigiriya terracotta tone looks breathtaking against sun-kissed skin and gold accessories.",
        date: "2026-06-11",
        verified: true,
        helpfulCount: 31,
        fit: "true",
        photos: ["/images/serendipity/celestial-terracotta-skirt.jpg"],
      },
      {
        id: "cb-rev-2",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Dilini A.",
        reviewerLocation: "Canberra, ACT",
        rating: 5,
        title: "Zero ironing required — best travel companion",
        body: "The natural crinkle linen texture is so forgiving. Rolled it into my weekend tote for a trip down the coast, shook it out, and wore it straight to lunch.",
        date: "2026-05-16",
        verified: true,
        helpfulCount: 22,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-3",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Giselle Moreau",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Like wearing living ancient art",
        body: "The rich earth pigment colour reminds me of natural ochre paints. Sits comfortably at the high waist and swishes delightfully as you stride.",
        date: "2026-04-08",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-4",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Marlo Jenkins",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Rich earthy tone, generous waist stretch",
        body: "The gathered waistband has plenty of give. If you're between sizes, you can safely take the smaller size for a snugger fit at the ribs.",
        date: "2026-02-21",
        verified: true,
        helpfulCount: 9,
        fit: "large",
        photos: [],
      },
      {
        id: "cb-rev-5",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Jessica Lim",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Warm and radiant",
        body: "Received so many compliments when paired with a simple black knit top and leather slides during MONA weekend.",
        date: "2025-12-14",
        verified: false,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-6",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Sasha Broadbent",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "A statement piece that feels grounded",
        body: "The fabric weight is substantial yet allows air circulation. Easily one of my top 3 wardrobe items this year.",
        date: "2025-10-09",
        verified: true,
        helpfulCount: 11,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "tea-leaf-two-piece",
    name: "A Leaf Unfolds Linen Set",
    category: "Two Piece Sets",
    story: "A Leaf Unfolds",
    storyPlace: "The Ceylon Tea Hills",
    destinations: ["Garden", "City"],
    colorName: "Tea Leaf Olive",
    colorHex: "#5E6C52",
    palette: ["#5E6C52", "#DCC7AF", "#F6F5F2"],
    fabric: "100% Breathable Organic Linen",
    priceAud: 290,
    image: "/images/serendipity/tea-leaf-two-piece.jpg",
    imageHover: "/images/serendipity/tea-leaf-two-piece-hover.jpg",
    videoHover: "/videos/serendipity/tea-leaf-two-piece-hover.mp4",
    gallery: [
      "/images/serendipity/tea-leaf-two-piece.jpg",
      "/images/serendipity/tea-leaf-two-piece-hover.jpg",
      "/images/serendipity/tea-leaf-two-piece-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "From Sri Lanka's high tea hills. A curved-yoke crop paired with an effortless tiered skirt.",
    heritage:
      "From one tender leaf, an entire landscape quietly unfolds. Ceylon's high-altitude tea hills give this olive linen set its sense of growth, contour and gentle movement — a curved-yoke crop and a flowing tiered skirt that breathe with you.",
    quote: "From one tender leaf, an entire landscape quietly unfolds.",
    craftDetails: [
      "Curved crop yoke",
      "Gathered natural waist skirt",
      "Natural coconut buttons",
      "Two-piece, worn together or apart",
    ],
    care: ["Cold machine wash", "Line dry in shade", "Warm iron"],
    reviews: [
      {
        id: "tl-rev-1",
        productId: "tea-leaf-two-piece",
        reviewerName: "Freya B.",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Two pieces, limitless wardrobe versatility",
        body: "I wear the curved-yoke crop with high-waisted denim for Saturday markets, and the tiered skirt with a white linen shirt for the office. Worn together, it looks like a bespoke runway set. Natural coconut buttons are such a thoughtful touch.",
        date: "2026-07-06",
        verified: true,
        helpfulCount: 36,
        fit: "true",
        photos: ["/images/serendipity/tea-leaf-two-piece.jpg"],
      },
      {
        id: "tl-rev-2",
        productId: "tea-leaf-two-piece",
        reviewerName: "Meera V.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "That deep misty olive green",
        body: "The shade of green is phenomenal — brings to mind the misty tea estates of Nuwara Eliya. Pure organic linen that feels cool on the skin even under direct sun.",
        date: "2026-05-30",
        verified: true,
        helpfulCount: 23,
        fit: "true",
        photos: [],
      },
      {
        id: "tl-rev-3",
        productId: "tea-leaf-two-piece",
        reviewerName: "Alannah Vance",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "The curved yoke cut is so flattering",
        body: "The crop top does not feel overly revealing; it hits just at the top edge of the high-rise skirt waistband. Flattering from every single angle.",
        date: "2026-04-22",
        verified: true,
        helpfulCount: 17,
        fit: "true",
        photos: ["/images/serendipity/tea-leaf-two-piece-hover.jpg"],
      },
      {
        id: "tl-rev-4",
        productId: "tea-leaf-two-piece",
        reviewerName: "Ananya Samarasinghe",
        reviewerLocation: "Brisbane, QLD",
        rating: 4,
        title: "Linen quality is outstanding",
        body: "Thick enough to have zero see-through issues, but soft enough to drape naturally without feeling stiff.",
        date: "2026-03-18",
        verified: true,
        helpfulCount: 12,
        fit: "true",
        photos: [],
      },
      {
        id: "tl-rev-5",
        productId: "tea-leaf-two-piece",
        reviewerName: "Gemma C.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Wore it all summer long",
        body: "Easily my favourite investment set of the season. Hand-washed multiple times and the linen has only gotten softer.",
        date: "2026-02-11",
        verified: true,
        helpfulCount: 15,
        fit: "true",
        photos: [],
      },
      {
        id: "tea-leaf-two-piece-rev-6",
        productId: "tea-leaf-two-piece",
        reviewerName: "Tessa Sterling",
        reviewerLocation: "Perth, WA",
        rating: 3,
        title: "Top band runs firm across the ribcage",
        body: "The skirt is 5 stars with deep pockets and a comfortable waistband. However, the crop top runs firm under the arms and across the ribcage. Definitely size up if you are broad-backed.",
        date: "2025-11-04",
        verified: true,
        helpfulCount: 19,
        fit: "small",
        photos: [],
      },
    ],
  },
];

export const CATEGORIES: (Category | "All")[] = [
  "All",
  "Dresses",
  "Tops & Blouses",
  "Skirts & Pants",
  "Two Piece Sets",
];

export interface DestinationMeta {
  key: Destination;
  label: string;
  tagline: string;
}

export const DESTINATIONS: DestinationMeta[] = [
  { key: "Beach", label: "Beach & Coast", tagline: "Airy linens, ocean blues" },
  { key: "Party", label: "Evening & Party", tagline: "Satin drape, warm glow" },
  { key: "City", label: "City & Work", tagline: "Tailored, easy structure" },
  { key: "Garden", label: "Garden & Day", tagline: "Soft florals, calm tones" },
  { key: "Everyday", label: "Everyday Ease", tagline: "Wear-anywhere staples" },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === slug);
}

export function getAverageRating(product: Product): number {
  if (!product.reviews || product.reviews.length === 0) return 0;
  const sum = product.reviews.reduce((acc, r) => acc + r.rating, 0);
  return sum / product.reviews.length;
}

export function getStoreReviewsAggregate(): { averageRating: number; totalReviews: number } {
  const allReviews = PRODUCTS.flatMap((p) => p.reviews || []);
  const totalReviews = allReviews.length;
  const averageRating =
    totalReviews > 0
      ? Number((allReviews.reduce((sum, r) => sum + r.rating, 0) / totalReviews).toFixed(1))
      : 4.9;
  return { averageRating, totalReviews };
}
