// Central catalogue for the BINDY — Serendipity collection.
// One shared source of truth for the shop grid, quick-view modal and product pages.

export type Category =
  | "Dresses"
  | "Tops & Blouses"
  | "Skirts & Pants"
  | "Two Piece Sets";

export type Destination = "Beach" | "Party" | "City" | "Garden" | "Everyday";

export interface Review {
  id: string;
  productId: string;
  reviewerName: string;
  reviewerLocation: string; // e.g. "Brisbane, QLD"
  rating: 1 | 2 | 3 | 4 | 5;
  title: string;
  body: string;
  date: string; // ISO format, must be a real past date (not future-dated)
  verified: boolean;
  helpfulCount: number;
  fit: "small" | "true" | "large";
  photos?: string[]; // optional customer photo URLs, leave empty array if none
}

export interface Product {
  id: string; // also used as the URL slug
  name: string;
  category: Category;
  story: string; // the poetic collection chapter name
  storyPlace: string; // the heritage place it draws from
  destinations: Destination[];
  colorName: string;
  colorHex: string;
  palette: string[]; // supporting swatch hexes
  fabric: string;
  priceAud: number;
  image: string; // primary
  imageHover: string; // shown on card hover
  videoHover?: string; // optional short clip played on card hover (falls back to imageHover)
  gallery: string[]; // full gallery for the product page (incl. image + hover)
  sizes: string[];
  description: string; // short card / modal blurb
  heritage: string; // long narrative for the product page
  quote: string; // one poetic line from the concept board
  craftDetails: string[];
  care: string[];
  reviews: Review[];
}

const AU_SIZES = ["AU 6 (XS)", "AU 8 (S)", "AU 10 (M)", "AU 12 (L)", "AU 14 (XL)"];

export const PRODUCTS: Product[] = [
  {
    id: "lotus-memory-dress",
    name: "Lotus Memory Strapless Dress",
    category: "Dresses",
    story: "Fragment of Memories",
    storyPlace: "The Lotus Ponds of Sri Lanka",
    destinations: ["Garden", "Everyday"],
    colorName: "Lotus Pink",
    colorHex: "#E8B7C3",
    palette: ["#E8B7C3", "#F6F5F2", "#DCC7AF"],
    fabric: "Lightweight Cotton Voile",
    priceAud: 240,
    image: "/images/serendipity/lotus-memory-dress.jpg",
    imageHover: "/images/serendipity/lotus-memory-dress-hover.jpg",
    videoHover: "/videos/serendipity/lotus-memory-dress-hover.mp4",
    gallery: [
      "/images/serendipity/lotus-memory-dress.jpg",
      "/images/serendipity/lotus-memory-dress-hover.jpg",
      "/images/serendipity/lotus-memory-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by Sri Lankan lotus ponds. A structured bodice reflecting inner strength, softened by a gathered skirt that unfolds like petals.",
    heritage:
      "Inspired by the still lotus ponds of Sri Lanka, where every memory blooms in its own time. The structured bodice mirrors quiet inner strength, while the softly gathered skirt opens like petals reaching for the morning sun — a piece made to be worn slowly, and remembered.",
    quote: "Every memory blooms in its own time.",
    craftDetails: [
      "Princess seams for a sculpted bodice",
      "Soft petal gathers through the skirt",
      "Concealed side zipper",
      "Fully lined for opacity",
    ],
    care: ["Gentle cold machine wash", "Line dry in shade", "Warm iron on reverse"],
    reviews: [
      {
        id: "lm-rev-1",
        productId: "lotus-memory-dress",
        reviewerName: "Amara P.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Feels like a quiet memory",
        body: "The lightweight cotton voile is so featherlight I forget I'm wearing it. Wore it to a botanical garden lunch in New Farm and three people asked where it was from. The petal gathering falls effortlessly.",
        date: "2026-07-14",
        verified: true,
        helpfulCount: 24,
        fit: "true",
        photos: ["/images/serendipity/lotus-memory-dress.jpg"],
      },
      {
        id: "lm-rev-2",
        productId: "lotus-memory-dress",
        reviewerName: "Chloe M.",
        reviewerLocation: "Gold Coast, QLD",
        rating: 5,
        title: "That gathered skirt is pure poetry",
        body: "The movement is unreal. True to size, the AU 8 fits my frame beautifully without slipping down at the bust line. Perfect for balmy Queensland evenings by the water.",
        date: "2026-06-02",
        verified: true,
        helpfulCount: 18,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-3",
        productId: "lotus-memory-dress",
        reviewerName: "Elena Vasquez",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Incredible artisan finish",
        body: "You can truly tell this is slow fashion. The internal structuring is supportive yet soft, and the lotus pink hue has this subtle warmth under natural Australian sunlight.",
        date: "2026-05-18",
        verified: true,
        helpfulCount: 12,
        fit: "true",
        photos: ["/images/serendipity/lotus-memory-dress-hover.jpg"],
      },
      {
        id: "lm-rev-4",
        productId: "lotus-memory-dress",
        reviewerName: "Siobhan K.",
        reviewerLocation: "Sydney, NSW",
        rating: 4,
        title: "Sublime fabric, slightly snug across the bust",
        body: "I am between an AU 10 and 12 and opted for the 10. It fits like a glove around the waist but is slightly firm across the bust. I recommend sizing up if you have a larger cup size.",
        date: "2026-04-11",
        verified: true,
        helpfulCount: 9,
        fit: "small",
        photos: [],
      },
      {
        id: "lm-rev-5",
        productId: "lotus-memory-dress",
        reviewerName: "Zara Wickramasinghe",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Connecting both of my worlds",
        body: "Growing up between Colombo and Fremantle, wearing a dress that celebrates Ceylon lotus ponds in such an elevated, minimal silhouette brought a genuine smile to my face. Beautifully crafted.",
        date: "2026-03-24",
        verified: true,
        helpfulCount: 31,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-6",
        productId: "lotus-memory-dress",
        reviewerName: "Sophie Lin",
        reviewerLocation: "Adelaide, SA",
        rating: 4,
        title: "Effortless elegance for a Barossa winery afternoon",
        body: "Wore this for a weekend in the Barossa Valley. Paired with flat leather sandals and an unbuttoned linen overshirt. Only note is that it requires gentle steaming after suitcase travel.",
        date: "2026-02-09",
        verified: true,
        helpfulCount: 5,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-7",
        productId: "lotus-memory-dress",
        reviewerName: "Hannah De Silva",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Drapes like a dream",
        body: "The cotton lining is completely opaque and so soft against the skin. Great length on my 168cm frame. Washed gently on cold cycle and it kept its texture beautifully.",
        date: "2025-12-19",
        verified: false,
        helpfulCount: 7,
        fit: "true",
        photos: [],
      },
      {
        id: "lm-rev-8",
        productId: "lotus-memory-dress",
        reviewerName: "Lucinda Grey",
        reviewerLocation: "Byron Bay, NSW",
        rating: 3,
        title: "Gorgeous piece, wished it had hidden pockets",
        body: "The cotton voile and bodice craftsmanship are 5-star quality without question. I only gave 3 stars because I really wish a casual strapless summer dress at this price point included concealed side pockets.",
        date: "2025-10-30",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "serendib-pearl-dress",
    name: "The Island Pearl Maxi Dress",
    category: "Dresses",
    story: "The Serendib Pearl",
    storyPlace: "The Coastal Waters of Serendib",
    destinations: ["Beach", "Party"],
    colorName: "Ivory White",
    colorHex: "#F6F5F2",
    palette: ["#F6F5F2", "#DCC7AF", "#C8D8E6"],
    fabric: "Pure Cotton with Cutwork Lace",
    priceAud: 285,
    image: "/images/serendipity/serendib-pearl-dress.jpg",
    imageHover: "/images/serendipity/serendib-pearl-dress-hover.jpg",
    videoHover: "/videos/serendipity/serendib-pearl-dress-hover.mp4",
    gallery: [
      "/images/serendipity/serendib-pearl-dress.jpg",
      "/images/serendipity/serendib-pearl-dress-hover.jpg",
      "/images/serendipity/serendib-pearl-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "A celebration of coastal pearl lustre. Hand-cut lace along the neckline and a sweeping cutwork scallop hem.",
    heritage:
      "Hidden beneath the waters of Serendib, the pearl waits — an unexpected treasure revealed only by quiet beauty. Cutwork lace and a gently gathered waist echo shell texture and the slow movement of the ocean, carrying that lustre from the shore into your wardrobe.",
    quote: "Hidden beneath the water, an unexpected treasure of quiet beauty.",
    craftDetails: [
      "Hand-cut cutwork lace neckline",
      "Gathered empire waist",
      "Scalloped cutwork hem",
      "Adjustable back tie",
    ],
    care: ["Hand wash cold", "Do not bleach", "Cool iron lace on reverse"],
    reviews: [
      {
        id: "sp-rev-1",
        productId: "serendib-pearl-dress",
        reviewerName: "Isabelle R.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Wore it to a coastal wedding at Wategos",
        body: "Photographs like an absolute dream and stayed completely breathable in 28-degree coastal humidity. The hand-cut cutwork lace is heirloom quality — not mass produced in the slightest.",
        date: "2026-07-20",
        verified: true,
        helpfulCount: 42,
        fit: "true",
        photos: ["/images/serendipity/serendib-pearl-dress.jpg"],
      },
      {
        id: "sp-rev-2",
        productId: "serendib-pearl-dress",
        reviewerName: "Priya S.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Serene, luminous ivory cotton",
        body: "The tone is a soft, natural ivory rather than a clinical stark white. The scallop hem skims just above the floor when barefoot. Completely enamored with the details.",
        date: "2026-06-15",
        verified: true,
        helpfulCount: 20,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-3",
        productId: "serendib-pearl-dress",
        reviewerName: "Charlotte Vance",
        reviewerLocation: "Noosa, QLD",
        rating: 5,
        title: "The back tie detail is perfection",
        body: "Allows you to adjust the fit through the bust and ribcage exactly as you want. I wore it for our beachfront anniversary dinner and felt so poised and relaxed.",
        date: "2026-05-04",
        verified: true,
        helpfulCount: 15,
        fit: "true",
        photos: ["/images/serendipity/serendib-pearl-dress-hover.jpg"],
      },
      {
        id: "sp-rev-4",
        productId: "serendib-pearl-dress",
        reviewerName: "Maya Perera",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Slightly generous length for petite frames",
        body: "The dress is magnificent. I am 160cm so I had it taken up 2 inches at the local tailor, but the cutwork scallop detail remained intact. Worth every cent.",
        date: "2026-04-02",
        verified: true,
        helpfulCount: 11,
        fit: "large",
        photos: [],
      },
      {
        id: "sp-rev-5",
        productId: "serendib-pearl-dress",
        reviewerName: "Harriet Cole",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Heirloom piece to keep forever",
        body: "You feel the artisan hands in every single stitch of cutwork. A timeless summer staple that outlasts transient fast-fashion trends.",
        date: "2026-02-18",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-6",
        productId: "serendib-pearl-dress",
        reviewerName: "Gemma Thorne",
        reviewerLocation: "Cairns, QLD",
        rating: 5,
        title: "Breathable tropical luxury",
        body: "Pure cotton that lets the ocean breeze flow right through. The lace on the neckline frames the collarbones exquisitely.",
        date: "2025-11-28",
        verified: false,
        helpfulCount: 4,
        fit: "true",
        photos: [],
      },
      {
        id: "sp-rev-7",
        productId: "serendib-pearl-dress",
        reviewerName: "Annabelle Scott",
        reviewerLocation: "Brisbane, QLD",
        rating: 4,
        title: "Pure elegance, lace needs delicate care",
        body: "The craftsmanship is remarkable. Just be mindful when washing — strictly hand-wash cold to preserve the intricate cutwork edges.",
        date: "2025-09-14",
        verified: true,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "pettah-check-dress",
    name: "A Pettah Discovery A-Line Dress",
    category: "Dresses",
    story: "A Pettah Discovery",
    storyPlace: "The Red Mosque, Pettah",
    destinations: ["City", "Everyday"],
    colorName: "Crimson Check",
    colorHex: "#A82B35",
    palette: ["#A82B35", "#F6F5F2", "#AFC8B1"],
    fabric: "Handwoven Cotton Gingham",
    priceAud: 220,
    image: "/images/serendipity/pettah-check-dress.jpg",
    imageHover: "/images/serendipity/pettah-check-dress-hover.jpg",
    videoHover: "/videos/serendipity/pettah-check-dress-hover.mp4",
    gallery: [
      "/images/serendipity/pettah-check-dress.jpg",
      "/images/serendipity/pettah-check-dress-hover.jpg",
      "/images/serendipity/pettah-check-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by Colombo's candy-striped Red Mosque. An architectural notched collar and tailored button rhythm.",
    heritage:
      "Among Pettah's restless streets stands the candy-striped Jumma Mosque, its red-and-white arches unmistakable against the noise. That rhythm of pattern, contrast and architecture shapes this notched-collar, A-line dress — a quiet discovery carried out of the old city.",
    quote: "Among Pettah's restless streets, an unexpected pattern stops you.",
    craftDetails: [
      "Notched lapel collar",
      "Covered button front placket",
      "A-line silhouette with waist seam",
      "Handwoven gingham, yarn-dyed",
    ],
    care: ["Cold machine wash", "Line dry", "Warm iron"],
    reviews: [
      {
        id: "pc-rev-1",
        productId: "pettah-check-dress",
        reviewerName: "Georgia T.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Flattering, architectural cut",
        body: "The notched collar and covered button placket give it such a chic tailored feel without losing the relaxed comfort of handloom cotton. Wear it to my design studio and on weekend gallery walks.",
        date: "2026-06-25",
        verified: true,
        helpfulCount: 29,
        fit: "true",
        photos: ["/images/serendipity/pettah-check-dress.jpg"],
      },
      {
        id: "pc-rev-2",
        productId: "pettah-check-dress",
        reviewerName: "Hannah W.",
        reviewerLocation: "Adelaide, SA",
        rating: 5,
        title: "Everyday favourite for city & market days",
        body: "Bought it for work, now I find myself reaching for it every Saturday morning. The handwoven gingham has substantial weight while remaining crisp and airy.",
        date: "2026-05-12",
        verified: true,
        helpfulCount: 16,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-3",
        productId: "pettah-check-dress",
        reviewerName: "Natasha Mendis",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "The Red Mosque inspiration is spot on",
        body: "Such a clever homage to Colombo heritage. The crimson tone is vibrant yet sophisticated, not overwhelming. AU 10 fits true to size.",
        date: "2026-04-19",
        verified: true,
        helpfulCount: 22,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-4",
        productId: "pettah-check-dress",
        reviewerName: "Tegan Brooks",
        reviewerLocation: "Canberra, ACT",
        rating: 4,
        title: "Smart and structured for the office",
        body: "Holds its shape throughout an 8-hour workday. The waist seam hits at the most flattering point. Very pleased with the quality.",
        date: "2026-03-08",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-5",
        productId: "pettah-check-dress",
        reviewerName: "Clara Bennett",
        reviewerLocation: "Gold Coast, QLD",
        rating: 4,
        title: "Love the covered buttons and lapel",
        body: "Deeply impressed with the finish. The covered buttons are a gorgeous artisan touch. Fabric feels durable and natural.",
        date: "2026-01-14",
        verified: true,
        helpfulCount: 3,
        fit: "true",
        photos: [],
      },
      {
        id: "pc-rev-6",
        productId: "pettah-check-dress",
        reviewerName: "Anouk Senanayake",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Wore it straight off the plane",
        body: "Travels exceptionally well. Ironed with light steam and it looked brand new immediately. High rotation in my wardrobe.",
        date: "2025-11-20",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "ocean-embraced-tiered-dress",
    name: "Embraced By Blue Tiered Maxi",
    category: "Dresses",
    story: "Embraced by Blue",
    storyPlace: "Where the Island Meets the Ocean",
    destinations: ["Beach", "Everyday"],
    colorName: "Washed Sea Blue",
    colorHex: "#2F4F6F",
    palette: ["#2F4F6F", "#C8D8E6", "#F6F5F2"],
    fabric: "Chambray Weave Cotton",
    priceAud: 260,
    image: "/images/serendipity/ocean-embraced-tiered-dress.jpg",
    imageHover: "/images/serendipity/ocean-embraced-tiered-dress-hover.jpg",
    videoHover: "/videos/serendipity/ocean-embraced-tiered-dress-hover.mp4",
    gallery: [
      "/images/serendipity/ocean-embraced-tiered-dress.jpg",
      "/images/serendipity/ocean-embraced-tiered-dress-hover.jpg",
      "/images/serendipity/ocean-embraced-tiered-dress-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Where the island meets the sea. Soft washed chambray woven in gathered wave tiers for sun-drenched days.",
    heritage:
      "When the island meets the ocean, an endless blue journey quietly begins. Washed chambray falls in gathered wave tiers — freedom, movement and calm woven into a maxi made for long, sun-drenched Australian days by the water.",
    quote: "When the island cries, an endless blue journey quietly begins.",
    craftDetails: [
      "Gathered wave tiers",
      "Shell button placket",
      "Relaxed coastal drape",
      "Breathable chambray weave",
    ],
    care: ["Cold machine wash", "Line dry in shade", "Warm iron"],
    reviews: [
      {
        id: "ob-rev-1",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Maddie L.",
        reviewerLocation: "Sunshine Coast, QLD",
        rating: 5,
        title: "My quintessential coastal uniform",
        body: "The tiers move like ocean waves in the sea breeze. Genuinely cool to wear during 32-degree coastal heatwaves. The genuine shell buttons catch the morning sunlight subtly.",
        date: "2026-07-08",
        verified: true,
        helpfulCount: 38,
        fit: "true",
        photos: ["/images/serendipity/ocean-embraced-tiered-dress.jpg"],
      },
      {
        id: "ob-rev-2",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Sana K.",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "That deep washed indigo hue",
        body: "The washed sea blue colour is even richer in person. Roomy and ultra comfortable without looking shapeless. AU 10 fits true to size.",
        date: "2026-06-01",
        verified: true,
        helpfulCount: 19,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-3",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Ailsa MacLeod",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "From Bondi morning coffee to sunset drinks",
        body: "Throws on effortlessly over swimwear with sandals, or dresses up with gold statement earrings for evening cocktails. The chambray softens with every wash.",
        date: "2026-04-27",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-4",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Kavitha R.",
        reviewerLocation: "Darwin, NT",
        rating: 5,
        title: "Survives tropical humidity effortlessly",
        body: "Living up north, finding dresses that truly breathe is essential. This chambray weave is a lifesaver. Pure comfort from dawn till dusk.",
        date: "2026-03-15",
        verified: true,
        helpfulCount: 9,
        fit: "true",
        photos: [],
      },
      {
        id: "ob-rev-5",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Lucy Sterling",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Generous flow, consider sizing down if between sizes",
        body: "Beautiful relaxed cut. If you prefer a closer fit across the chest and shoulders you could consider sizing down, but I adore the breezy silhouette.",
        date: "2026-02-02",
        verified: true,
        helpfulCount: 12,
        fit: "large",
        photos: [],
      },
      {
        id: "ob-rev-6",
        productId: "ocean-embraced-tiered-dress",
        reviewerName: "Bridie O'Connor",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Coastal perfection with weighted hem",
        body: "The craft and hem weight are second to none. It billows gracefully in the ocean wind rather than flying up wildly.",
        date: "2025-11-10",
        verified: false,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "shore-traces-blouse",
    name: "Traces in the Sand Peplum Top",
    category: "Tops & Blouses",
    story: "Traces in the Sand",
    storyPlace: "The Sri Lankan Shore",
    destinations: ["Beach", "City"],
    colorName: "Sand Beige Check",
    colorHex: "#DCC7AF",
    palette: ["#DCC7AF", "#F6F5F2", "#A46446"],
    fabric: "Fine Handloom Cotton",
    priceAud: 175,
    image: "/images/serendipity/shore-traces-blouse.jpg",
    imageHover: "/images/serendipity/shore-traces-blouse-hover.jpg",
    videoHover: "/videos/serendipity/shore-traces-blouse-hover.mp4",
    gallery: [
      "/images/serendipity/shore-traces-blouse.jpg",
      "/images/serendipity/shore-traces-blouse-hover.jpg",
      "/images/serendipity/shore-traces-blouse-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Tidal ripple motifs and soft sand checks, shaped with a peplum hem and corsetry-inspired seams.",
    heritage:
      "With every returning tide, the sand reveals a pattern never seen before. Shoreline lines and tidal ripples shape this peplum of fine sand-check handloom — structured yet soft, a trace of the shore you can carry into the city.",
    quote: "With every returning tide, the sand reveals a pattern never seen before.",
    craftDetails: [
      "Shaped peplum hem",
      "Fine woven sand check",
      "Adjustable rear ties",
      "Structural corsetry seams",
    ],
    care: ["Hand wash cold", "Line dry", "Cool iron"],
    reviews: [
      {
        id: "st-rev-1",
        productId: "shore-traces-blouse",
        reviewerName: "Ella F.",
        reviewerLocation: "Newcastle, NSW",
        rating: 5,
        title: "Sculptural yet supremely comfortable",
        body: "The corsetry-inspired seams give definition without any pinching or rigid wire. The peplum flare sits perfectly over high-waist tailored linen trousers.",
        date: "2026-06-18",
        verified: true,
        helpfulCount: 27,
        fit: "true",
        photos: ["/images/serendipity/shore-traces-blouse.jpg"],
      },
      {
        id: "st-rev-2",
        productId: "shore-traces-blouse",
        reviewerName: "Ruwani J.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Unrivalled handloom texture",
        body: "You can feel the artisan weave between your fingers. It holds crisp structure while remaining soft. The rear tie lets you cinch to your exact waistline.",
        date: "2026-05-23",
        verified: true,
        helpfulCount: 18,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-3",
        productId: "shore-traces-blouse",
        reviewerName: "Miriam Al-Hassan",
        reviewerLocation: "Sydney, NSW",
        rating: 4,
        title: "Exquisite details, back tie takes a moment",
        body: "Once you adjust the rear ties it fits like custom tailoring. The sand check is such a soothing, warm neutral that pairs with everything.",
        date: "2026-03-30",
        verified: true,
        helpfulCount: 10,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-4",
        productId: "shore-traces-blouse",
        reviewerName: "Penelope Cross",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Elevates any simple trouser or skirt",
        body: "Instantly makes any outfit look styled and considered. Received so many compliments during a corporate lunch in the city.",
        date: "2026-02-14",
        verified: true,
        helpfulCount: 8,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-5",
        productId: "shore-traces-blouse",
        reviewerName: "Tahnee Miller",
        reviewerLocation: "Adelaide, SA",
        rating: 4,
        title: "Wore it to an afternoon tea",
        body: "Felt so refined. The peplum proportion is modern and fresh. Handloom weave breathes well in warm rooms.",
        date: "2025-12-05",
        verified: true,
        helpfulCount: 4,
        fit: "true",
        photos: [],
      },
      {
        id: "st-rev-6",
        productId: "shore-traces-blouse",
        reviewerName: "Belinda Harris",
        reviewerLocation: "Perth, WA",
        rating: 3,
        title: "Careful if you have a broader back",
        body: "The peplum top is stunning in construction. I found it slightly snug across the upper back when reaching forward, so consider sizing up if you are broad-shouldered.",
        date: "2025-10-18",
        verified: true,
        helpfulCount: 11,
        fit: "small",
        photos: [],
      },
    ],
  },
  {
    id: "cinnamon-flow-skirt",
    name: "Cinnamon Flow Bias Maxi Skirt",
    category: "Skirts & Pants",
    story: "Cinnamon Flow",
    storyPlace: "The Ceylon Cinnamon Gardens",
    destinations: ["Party", "City"],
    colorName: "Cinnamon Satin",
    colorHex: "#A46446",
    palette: ["#A46446", "#F6F5F2", "#DCC7AF"],
    fabric: "Recycled Silk & Lyocell Blend",
    priceAud: 195,
    image: "/images/serendipity/cinnamon-flow-skirt.jpg",
    imageHover: "/images/serendipity/cinnamon-flow-skirt-hover.jpg",
    videoHover: "/videos/serendipity/cinnamon-flow-skirt-hover.mp4",
    gallery: [
      "/images/serendipity/cinnamon-flow-skirt.jpg",
      "/images/serendipity/cinnamon-flow-skirt-hover.jpg",
      "/images/serendipity/cinnamon-flow-skirt-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Rich cinnamon spice with earthy undertones, draped in a fluid bias cut for maximum grace.",
    heritage:
      "Drawn from the bark of Ceylon cinnamon — warm, grounding and quietly luxurious. A fluid bias cut lets the spice-brown silk move like poured honey, catching the light with every step from dinner to the dance floor.",
    quote: "Warm, grounding, and quietly luxurious.",
    craftDetails: [
      "Bias-cut fluid drape",
      "Elasticated internal waistband",
      "French seams throughout",
      "Recycled silk blend",
    ],
    care: ["Dry clean, or gentle hand wash cold", "Line dry flat", "Cool iron"],
    reviews: [
      {
        id: "cf-rev-1",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Tara D.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Moves like poured liquid amber",
        body: "The bias cut on this skirt is masterfully drafted. It glides across the hips without clinging or bunching. Wore it to an evening dinner by Sydney harbour and caught the amber sunset reflections.",
        date: "2026-07-02",
        verified: true,
        helpfulCount: 34,
        fit: "true",
        photos: ["/images/serendipity/cinnamon-flow-skirt.jpg"],
      },
      {
        id: "cf-rev-2",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Nadia H.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Effortlessly elegant & comfortable all evening",
        body: "The secret elasticated inner waistband is a triumph — looks completely seamless from the exterior but provides total ease during a multi-course dinner.",
        date: "2026-05-28",
        verified: true,
        helpfulCount: 21,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-3",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Victoria Sterling",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "French seams and luxury weighting",
        body: "The quality of craftsmanship inside is as stunning as the outside. French seams everywhere. The cinnamon hue pairs wonderfully with cream knits or black camisoles.",
        date: "2026-04-15",
        verified: true,
        helpfulCount: 16,
        fit: "true",
        photos: ["/images/serendipity/cinnamon-flow-skirt-hover.jpg"],
      },
      {
        id: "cf-rev-4",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Danielle Cox",
        reviewerLocation: "Gold Coast, QLD",
        rating: 4,
        title: "Sensational silk-blend hand feel",
        body: "Silky and soft. The length hits right above the ankle bone on me (172cm). Hand-washed in cool water and it retained its sheen perfectly.",
        date: "2026-03-11",
        verified: true,
        helpfulCount: 11,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-5",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Ashwini Jayatilleke",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Ceylon spice at its most refined",
        body: "Deep, earthy, glowing cinnamon. You cannot find this unique shade in fast-fashion chain stores. Absolutely sublime piece.",
        date: "2026-02-04",
        verified: true,
        helpfulCount: 25,
        fit: "true",
        photos: [],
      },
      {
        id: "cf-rev-6",
        productId: "cinnamon-flow-skirt",
        reviewerName: "Keira Walsh",
        reviewerLocation: "Canberra, ACT",
        rating: 4,
        title: "Stunning skirt, slightly relaxed waist",
        body: "Very flattering line. I sized down to AU 8 for a firmer fit around the high waist and it sat impeccably.",
        date: "2025-11-19",
        verified: false,
        helpfulCount: 5,
        fit: "large",
        photos: [],
      },
    ],
  },
  {
    id: "celestial-terracotta-skirt",
    name: "Celestial Bloom Pleated Maxi",
    category: "Skirts & Pants",
    story: "Celestial Bloom",
    storyPlace: "The Sigiriya Frescoes",
    destinations: ["Party", "Garden"],
    colorName: "Sigiriya Terracotta",
    colorHex: "#B86B4B",
    palette: ["#B86B4B", "#F6F5F2", "#DCC7AF"],
    fabric: "Crinkle Linen & Cotton",
    priceAud: 210,
    image: "/images/serendipity/celestial-terracotta-skirt.jpg",
    imageHover: "/images/serendipity/celestial-terracotta-skirt-hover.jpg",
    videoHover: "/videos/serendipity/celestial-terracotta-skirt-hover.mp4",
    gallery: [
      "/images/serendipity/celestial-terracotta-skirt.jpg",
      "/images/serendipity/celestial-terracotta-skirt-hover.jpg",
      "/images/serendipity/celestial-terracotta-skirt-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by the ancient Sigiriya frescoes. Rich terracotta hues with subtle pleated movement.",
    heritage:
      "Painted on an ancient rock wall, the maidens of Sigiriya still bloom after fifteen centuries. Terracotta hues and softly pleated movement carry their timeless grace forward into a maxi that feels both grounded and quietly celestial.",
    quote: "From an ancient painted wall, a timeless grace quietly reappears.",
    craftDetails: [
      "Gathered waistband",
      "Breathable crinkle finish",
      "Deep concealed side pockets",
      "Fluid pleated fall",
    ],
    care: ["Cold machine wash", "Line dry to keep crinkle", "No iron needed"],
    reviews: [
      {
        id: "cb-rev-1",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Bianca N.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Deep, functional pockets in a couture skirt!",
        body: "Finding genuine, generous pockets hidden within delicate pleats is a dream come true. The Sigiriya terracotta tone looks breathtaking against sun-kissed skin and gold accessories.",
        date: "2026-06-11",
        verified: true,
        helpfulCount: 31,
        fit: "true",
        photos: ["/images/serendipity/celestial-terracotta-skirt.jpg"],
      },
      {
        id: "cb-rev-2",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Dilini A.",
        reviewerLocation: "Canberra, ACT",
        rating: 5,
        title: "Zero ironing required — best travel companion",
        body: "The natural crinkle linen texture is so forgiving. Rolled it into my weekend tote for a trip down the coast, shook it out, and wore it straight to lunch.",
        date: "2026-05-16",
        verified: true,
        helpfulCount: 22,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-3",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Giselle Moreau",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Like wearing living ancient art",
        body: "The rich earth pigment colour reminds me of natural ochre paints. Sits comfortably at the high waist and swishes delightfully as you stride.",
        date: "2026-04-08",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-4",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Marlo Jenkins",
        reviewerLocation: "Melbourne, VIC",
        rating: 4,
        title: "Rich earthy tone, generous waist stretch",
        body: "The gathered waistband has plenty of give. If you're between sizes, you can safely take the smaller size for a snugger fit at the ribs.",
        date: "2026-02-21",
        verified: true,
        helpfulCount: 9,
        fit: "large",
        photos: [],
      },
      {
        id: "cb-rev-5",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Jessica Lim",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Warm and radiant",
        body: "Received so many compliments when paired with a simple black knit top and leather slides during MONA weekend.",
        date: "2025-12-14",
        verified: false,
        helpfulCount: 6,
        fit: "true",
        photos: [],
      },
      {
        id: "cb-rev-6",
        productId: "celestial-terracotta-skirt",
        reviewerName: "Sasha Broadbent",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "A statement piece that feels grounded",
        body: "The fabric weight is substantial yet allows air circulation. Easily one of my top 3 wardrobe items this year.",
        date: "2025-10-09",
        verified: true,
        helpfulCount: 11,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "tea-leaf-two-piece",
    name: "A Leaf Unfolds Linen Set",
    category: "Two Piece Sets",
    story: "A Leaf Unfolds",
    storyPlace: "The Ceylon Tea Hills",
    destinations: ["Garden", "City"],
    colorName: "Tea Leaf Olive",
    colorHex: "#5E6C52",
    palette: ["#5E6C52", "#DCC7AF", "#F6F5F2"],
    fabric: "100% Breathable Organic Linen",
    priceAud: 290,
    image: "/images/serendipity/tea-leaf-two-piece.jpg",
    imageHover: "/images/serendipity/tea-leaf-two-piece-hover.jpg",
    videoHover: "/videos/serendipity/tea-leaf-two-piece-hover.mp4",
    gallery: [
      "/images/serendipity/tea-leaf-two-piece.jpg",
      "/images/serendipity/tea-leaf-two-piece-hover.jpg",
      "/images/serendipity/tea-leaf-two-piece-full.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "From Sri Lanka's high tea hills. A curved-yoke crop paired with an effortless tiered skirt.",
    heritage:
      "From one tender leaf, an entire landscape quietly unfolds. Ceylon's high-altitude tea hills give this olive linen set its sense of growth, contour and gentle movement — a curved-yoke crop and a flowing tiered skirt that breathe with you.",
    quote: "From one tender leaf, an entire landscape quietly unfolds.",
    craftDetails: [
      "Curved crop yoke",
      "Gathered natural waist skirt",
      "Natural coconut buttons",
      "Two-piece, worn together or apart",
    ],
    care: ["Cold machine wash", "Line dry in shade", "Warm iron"],
    reviews: [
      {
        id: "tl-rev-1",
        productId: "tea-leaf-two-piece",
        reviewerName: "Freya B.",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Two pieces, limitless wardrobe versatility",
        body: "I wear the curved-yoke crop with high-waisted denim for Saturday markets, and the tiered skirt with a white linen shirt for the office. Worn together, it looks like a bespoke runway set. Natural coconut buttons are such a thoughtful touch.",
        date: "2026-07-06",
        verified: true,
        helpfulCount: 36,
        fit: "true",
        photos: ["/images/serendipity/tea-leaf-two-piece.jpg"],
      },
      {
        id: "tl-rev-2",
        productId: "tea-leaf-two-piece",
        reviewerName: "Meera V.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "That deep misty olive green",
        body: "The shade of green is phenomenal — brings to mind the misty tea estates of Nuwara Eliya. Pure organic linen that feels cool on the skin even under direct sun.",
        date: "2026-05-30",
        verified: true,
        helpfulCount: 23,
        fit: "true",
        photos: [],
      },
      {
        id: "tl-rev-3",
        productId: "tea-leaf-two-piece",
        reviewerName: "Alannah Vance",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "The curved yoke cut is so flattering",
        body: "The crop top does not feel overly revealing; it hits just at the top edge of the high-rise skirt waistband. Flattering from every single angle.",
        date: "2026-04-22",
        verified: true,
        helpfulCount: 17,
        fit: "true",
        photos: ["/images/serendipity/tea-leaf-two-piece-hover.jpg"],
      },
      {
        id: "tl-rev-4",
        productId: "tea-leaf-two-piece",
        reviewerName: "Ananya Samarasinghe",
        reviewerLocation: "Brisbane, QLD",
        rating: 4,
        title: "Linen quality is outstanding",
        body: "Thick enough to have zero see-through issues, but soft enough to drape naturally without feeling stiff.",
        date: "2026-03-18",
        verified: true,
        helpfulCount: 12,
        fit: "true",
        photos: [],
      },
      {
        id: "tl-rev-5",
        productId: "tea-leaf-two-piece",
        reviewerName: "Gemma C.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Wore it all summer long",
        body: "Easily my favourite investment set of the season. Hand-washed multiple times and the linen has only gotten softer.",
        date: "2026-02-11",
        verified: true,
        helpfulCount: 15,
        fit: "true",
        photos: [],
      },
      {
        id: "tea-leaf-two-piece-rev-6",
        productId: "tea-leaf-two-piece",
        reviewerName: "Tessa Sterling",
        reviewerLocation: "Perth, WA",
        rating: 3,
        title: "Top band runs firm across the ribcage",
        body: "The skirt is 5 stars with deep pockets and a comfortable waistband. However, the crop top runs firm under the arms and across the ribcage. Definitely size up if you are broad-backed.",
        date: "2025-11-04",
        verified: true,
        helpfulCount: 19,
        fit: "small",
        photos: [],
      },
    ],
  },
  {
    id: "golden-cascade-dress",
    name: "A Golden Cascade Tiered Shirt Dress",
    category: "Dresses",
    story: "A Golden Cascade",
    storyPlace: "The Ehela Blossoms of Kandy",
    destinations: ["Garden", "Everyday"],
    colorName: "Ehela Blossom",
    colorHex: "#EEDAA2",
    palette: ["#EEDAA2", "#F6F5F2", "#B86B4B"],
    fabric: "Textured Cotton Seersucker Voile",
    priceAud: 235,
    image: "/images/collection-2/golden-cascade-dress.jpg",
    imageHover: "/images/collection-2/golden-cascade-dress-hover.jpg",
    gallery: [
      "/images/collection-2/golden-cascade-dress.jpg",
      "/images/collection-2/golden-cascade-dress-hover.jpg",
      "/images/collection-2/golden-cascade-dress-2.jpg",
      "/images/collection-2/golden-cascade-dress-3.jpg",
      "/images/collection-2/golden-cascade-dress-4.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by Sri Lanka's sacred Ehela blossoms. A breezy collared shirt bodice with relaxed wave tiers in sunlight cotton seersucker.",
    heritage:
      "In the warm breezes of July and August, the Ehela trees of Sri Lanka burst into shimmering cascades of yellow blossoms — a harbinger of sacred festival season and quiet renewal. Designed with a tailored shirt collar and soft gathered tiers, this dress brings the warmth of Ceylon sunshine into effortless Australian high teas and weekend market strolls.",
    quote: "When the Ehela blooms, the island wears a canopy of pure golden light.",
    craftDetails: [
      "Tailored point collar with hidden button placket",
      "Triple-tiered gathered silhouette",
      "Lightweight textured seersucker weave",
      "Breathable unlined drape for balmy days",
    ],
    care: ["Gentle machine wash cold", "Line dry in shade", "Light steam or leave natural crinkle"],
    reviews: [
      {
        id: "gc-rev-1",
        productId: "golden-cascade-dress",
        reviewerName: "Amali S.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "Like wearing pure golden sunshine",
        body: "The soft butter yellow tone is exquisite. Wore it to a botanical garden brunch and received endless compliments. The seersucker texture keeps you cool all day.",
        date: "2026-08-01",
        verified: true,
        helpfulCount: 22,
        fit: "true",
        photos: ["/images/collection-2/golden-cascade-dress.jpg"],
      },
      {
        id: "gc-rev-2",
        productId: "golden-cascade-dress",
        reviewerName: "Isla Campbell",
        reviewerLocation: "Gold Coast, QLD",
        rating: 5,
        title: "Flattering tiers with zero clinging",
        body: "The collar adds that tailored touch, making it easy to dress up with mules or wear casually with white sneakers. AU 8 fits true to size.",
        date: "2026-07-22",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
      {
        id: "gc-rev-3",
        productId: "golden-cascade-dress",
        reviewerName: "Natasha G.",
        reviewerLocation: "Sydney, NSW",
        rating: 4,
        title: "Lovely fabric, slightly relaxed fit",
        body: "A gorgeous warm hue that complements summer skin. The silhouette is deliberately breezy, so if you prefer a close waist fit consider sizing down.",
        date: "2026-06-18",
        verified: true,
        helpfulCount: 8,
        fit: "large",
        photos: [],
      },
    ],
  },
  {
    id: "beyond-garden-wall-peplum",
    name: "Beyond the Garden Wall Peplum Top",
    category: "Tops & Blouses",
    story: "Beyond the Garden Wall",
    storyPlace: "The Sun-Bleached Walls of Galle Fort",
    destinations: ["Everyday", "City"],
    colorName: "Bougainvillea Fuchsia",
    colorHex: "#D81B60",
    palette: ["#D81B60", "#F6F5F2", "#1F1E1D"],
    fabric: "Crisp Structured Cotton Poplin",
    priceAud: 185,
    image: "/images/collection-2/beyond-garden-wall-peplum.jpg",
    imageHover: "/images/collection-2/beyond-garden-wall-peplum-hover.jpg",
    gallery: [
      "/images/collection-2/beyond-garden-wall-peplum.jpg",
      "/images/collection-2/beyond-garden-wall-peplum-hover.jpg",
      "/images/collection-2/beyond-garden-wall-peplum-1.jpg",
      "/images/collection-2/beyond-garden-wall-peplum-2.jpg",
      "/images/collection-2/beyond-garden-wall-peplum-3.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Inspired by bougainvillea spilling over colonial stone walls. A square-neck peplum cami with flattering waist gather in vibrant magenta (DR2444).",
    heritage:
      "Behind ancient limestone ramparts, vibrant bougainvillea escapes every border, tumbling in radiant magenta over sunlit walls. This structural peplum cami captures that lively spirit — architectural yet soft, tailored to pair effortlessly with high-waisted shorts, skirts, or denim.",
    quote: "Wild blooms know no walls — they spill outward in unrestrained joy.",
    craftDetails: [
      "Clean square neckline with slender straps",
      "Empire seam with flared peplum hem",
      "Pre-washed breathable poplin cotton",
      "Concealed side zip closure for seamless finish",
    ],
    care: ["Machine wash cold with like colours", "Hang dry in shade", "Medium warm iron"],
    reviews: [
      {
        id: "bgw-rev-1",
        productId: "beyond-garden-wall-peplum",
        reviewerName: "Clara R.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "The magenta tone is showstopping",
        body: "Pictures do not do this color justice. The peplum flares out just right over denim shorts or tailored trousers. Crisp, breathable cotton.",
        date: "2026-08-04",
        verified: true,
        helpfulCount: 19,
        fit: "true",
        photos: ["/images/collection-2/beyond-garden-wall-peplum.jpg"],
      },
      {
        id: "bgw-rev-2",
        productId: "beyond-garden-wall-peplum",
        reviewerName: "Zoe D.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Instant mood lifter",
        body: "Wore this for a sunny harbour lunch. The square neckline is so flattering on the collarbones and the fit through the bust is tailored perfectly.",
        date: "2026-07-15",
        verified: true,
        helpfulCount: 11,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "desert-rose-set",
    name: "Desert Rose Ribbed & Wrap Set",
    category: "Two Piece Sets",
    story: "Desert Rose",
    storyPlace: "The Mannar Coastal Dunes",
    destinations: ["Beach", "Everyday"],
    colorName: "Coral & Olive Moss",
    colorHex: "#E07A5F",
    palette: ["#E07A5F", "#6B7B4B", "#F6F5F2"],
    fabric: "Fine Ribbed Cotton & Washed Linen",
    priceAud: 245,
    image: "/images/collection-2/desert-rose-set.jpg",
    imageHover: "/images/collection-2/desert-rose-set-hover.jpg",
    gallery: [
      "/images/collection-2/desert-rose-set.jpg",
      "/images/collection-2/desert-rose-set-hover.jpg",
      "/images/collection-2/desert-rose-set-1.jpg",
      "/images/collection-2/desert-rose-set-2.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Sun-drenched coral ribbed tee paired with a washed olive linen wrap skirt featuring an adjustable sash tie. Code DR2445.",
    heritage:
      "Along the wind-sculpted sand spits of Mannar, resilient desert roses blossom against sun-baked earth and olive sea scrub. This tactile two-piece pairs a featherweight ribbed cotton tee with a versatile wrap skirt that adjusts comfortably to every hip contour.",
    quote: "From arid shores and shifting dunes, quiet resilience blooms.",
    craftDetails: [
      "Breathable micro-ribbed crew tee",
      "Wrap mini skirt with functional side sash tie",
      "Natural vegetable-dyed linen blend",
      "Mix-and-match capsule versatility",
    ],
    care: ["Cold gentle machine wash", "Line dry flat", "Warm iron skirt on reverse"],
    reviews: [
      {
        id: "dr-rev-1",
        productId: "desert-rose-set",
        reviewerName: "Kavindi F.",
        reviewerLocation: "Perth, WA",
        rating: 5,
        title: "Perfection in two versatile pieces",
        body: "The combination of warm coral ribbed jersey and earthy olive linen is so unexpected yet harmonious. The wrap skirt ties securely without slipping.",
        date: "2026-07-28",
        verified: true,
        helpfulCount: 26,
        fit: "true",
        photos: ["/images/collection-2/desert-rose-set.jpg"],
      },
      {
        id: "dr-rev-2",
        productId: "desert-rose-set",
        reviewerName: "Harper M.",
        reviewerLocation: "Adelaide, SA",
        rating: 5,
        title: "Casual luxury at its finest",
        body: "Wore this all weekend on Rottnest Island. The tee is feather-soft and the linen wrap skirt has great structure. High rotation piece.",
        date: "2026-06-30",
        verified: true,
        helpfulCount: 15,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "sunset-stroll-set",
    name: "Sunset Stroll Tiered Maxi Set",
    category: "Two Piece Sets",
    story: "Sunset Stroll",
    storyPlace: "The Galle Face Promenade",
    destinations: ["Beach", "Party"],
    colorName: "Sunset Tangerine & Onyx",
    colorHex: "#FA5F55",
    palette: ["#FA5F55", "#1F1E1D", "#EEDAA2"],
    fabric: "Crinkle Cotton & Ribbed Knit",
    priceAud: 275,
    image: "/images/collection-2/sunset-stroll-set.jpg",
    imageHover: "/images/collection-2/sunset-stroll-set-hover.jpg",
    gallery: [
      "/images/collection-2/sunset-stroll-set.jpg",
      "/images/collection-2/sunset-stroll-set-hover.jpg",
      "/images/collection-2/sunset-stroll-set-1.jpg",
      "/images/collection-2/sunset-stroll-set-2.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "A sculpted onyx scoop crop top paired with a radiant tangerine tiered maxi skirt that sways with coastal breezes.",
    heritage:
      "As daylight fades across Colombo's ocean promenade, the horizon ignites in fierce shades of melon and coral orange against the dusk sky. This two-piece captures that moment of celebration — grounded by a minimalist scoop crop and elevated by flowing tiered ripples of vibrant cotton.",
    quote: "The sun dips, the ocean sighs, and evening awakens.",
    craftDetails: [
      "High-stretch double-layered rib crop top",
      "Tiered maxi skirt with gentle elasticated waistband",
      "Lightweight crinkle texture that repels wrinkles",
      "Flattering movement with every stride",
    ],
    care: ["Machine wash cold inside out", "Line dry in shade", "No iron needed for skirt"],
    reviews: [
      {
        id: "ss-rev-1",
        productId: "sunset-stroll-set",
        reviewerName: "Tara K.",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "The skirt movement is breathtaking",
        body: "The vibrant sunset hue catches the light like molten gold at golden hour. The black scoop top fits comfortably and doesn't roll up.",
        date: "2026-08-02",
        verified: true,
        helpfulCount: 33,
        fit: "true",
        photos: ["/images/collection-2/sunset-stroll-set.jpg"],
      },
      {
        id: "ss-rev-2",
        productId: "sunset-stroll-set",
        reviewerName: "Gemma B.",
        reviewerLocation: "Byron Bay, NSW",
        rating: 5,
        title: "Dressed up for coastal cocktails",
        body: "Received so many questions about where this was from! The skirt has substantial fabric without feeling heavy in coastal warmth.",
        date: "2026-07-11",
        verified: true,
        helpfulCount: 18,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "sweet-breeze-dress",
    name: "Sweet Breeze Embroidered Sundress",
    category: "Dresses",
    story: "Sweet Breeze",
    storyPlace: "Verandahs of Old Matara",
    destinations: ["Garden", "Everyday"],
    colorName: "Pearl White",
    colorHex: "#F7F7F2",
    palette: ["#F7F7F2", "#DCC7AF", "#AFC8B1"],
    fabric: "Schiffli Embroidered Cotton Voile",
    priceAud: 225,
    image: "/images/collection-2/sweet-breeze-dress.jpg",
    imageHover: "/images/collection-2/sweet-breeze-dress-hover.jpg",
    gallery: [
      "/images/collection-2/sweet-breeze-dress.jpg",
      "/images/collection-2/sweet-breeze-dress-hover.jpg",
      "/images/collection-2/sweet-breeze-dress-1.jpg",
      "/images/collection-2/sweet-breeze-dress-2.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Delicate floral schiffli embroidery across airy cotton voile. Featuring a square neckline, slender straps, and a romantic gathered skirt.",
    heritage:
      "Under broad timber rafters on southern coastal verandahs, the afternoon trade winds carry the honeyed fragrance of jasmine and wild temple blossoms. Cut from heirloom-quality schiffli embroidered cotton, this sundress brings breezy innocence and quiet luxury to warm summer days.",
    quote: "A soft breeze through open doors whispers the afternoon awake.",
    craftDetails: [
      "Tone-on-tone botanical eyelet embroidery",
      "Comfortable smocked back panel for tailored fit",
      "Fully lined in ultra-soft organic cotton",
      "Slender adjustable shoulder ties",
    ],
    care: ["Hand wash or delicate cycle cold", "Line dry in shade", "Warm iron on reverse"],
    reviews: [
      {
        id: "sb-rev-1",
        productId: "sweet-breeze-dress",
        reviewerName: "Annabelle W.",
        reviewerLocation: "Hobart, TAS",
        rating: 5,
        title: "Heirloom embroidery in pure cotton",
        body: "The embroidery across this dress is so delicate and refined. Completely opaque lining so you don't have to worry in bright sunshine. Fits like a dream.",
        date: "2026-07-25",
        verified: true,
        helpfulCount: 27,
        fit: "true",
        photos: ["/images/collection-2/sweet-breeze-dress.jpg"],
      },
      {
        id: "sb-rev-2",
        productId: "sweet-breeze-dress",
        reviewerName: "Lucinda Grey",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "The quintessential summer white dress",
        body: "Light as air, beautifully tailored. Wore it to a high tea and felt poised yet completely comfortable.",
        date: "2026-06-21",
        verified: true,
        helpfulCount: 14,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "terra-essence-set",
    name: "Terra Essence Washed Linen Set",
    category: "Two Piece Sets",
    story: "Terra Essence",
    storyPlace: "The Potters of Kelaniya",
    destinations: ["Everyday", "City"],
    colorName: "Earth Mocha",
    colorHex: "#8B6D53",
    palette: ["#8B6D53", "#DCC7AF", "#1F1E1D"],
    fabric: "100% Breathable Washed Linen",
    priceAud: 295,
    image: "/images/collection-2/terra-essence-set.jpg",
    imageHover: "/images/collection-2/terra-essence-set-hover.jpg",
    gallery: [
      "/images/collection-2/terra-essence-set.jpg",
      "/images/collection-2/terra-essence-set-hover.jpg",
      "/images/collection-2/terra-essence-set-1.jpg",
      "/images/collection-2/terra-essence-set-2.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "A boxy cropped linen blouse with keyhole back detail paired with a voluminous tiered maxi skirt. Codes DR2422 & DR2423.",
    heritage:
      "Formed from the ancient riverbed clay of the Kelani River, natural earthenware pottery grounds Sri Lankan daily life. This rich earth-mocha linen set honors that tactile simplicity — pure unadorned luxury woven from flax fibers that breathe through the highest heat.",
    quote: "Return to the earth, where every enduring story takes root.",
    craftDetails: [
      "Short-sleeved crop blouse with delicate gathered shoulders",
      "Signature teardrop keyhole back button",
      "Voluminous tiered maxi skirt with flat front waistband",
      "Pre-washed for cloud-like softness from first wear",
    ],
    care: ["Gentle machine wash cold", "Line dry in shade", "Warm iron if desired or wear naturally textured"],
    reviews: [
      {
        id: "te-rev-1",
        productId: "terra-essence-set",
        reviewerName: "Nadia H.",
        reviewerLocation: "Canberra, ACT",
        rating: 5,
        title: "Sublime mocha hue and luxury linen",
        body: "The earth tone is rich, sophisticated, and neutral without feeling dull. The linen weight is substantial and drapes beautifully.",
        date: "2026-08-05",
        verified: true,
        helpfulCount: 29,
        fit: "true",
        photos: ["/images/collection-2/terra-essence-set.jpg"],
      },
      {
        id: "te-rev-2",
        productId: "terra-essence-set",
        reviewerName: "Freya C.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Wear together or separate endlessly",
        body: "The top works brilliantly with high-waisted white jeans, and the tiered maxi skirt pairs with everything from silk tanks to chunky knitwear.",
        date: "2026-07-09",
        verified: true,
        helpfulCount: 16,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "crimson-lotus-dress",
    name: "The Crimson Lotus Maxi Dress",
    category: "Dresses",
    story: "The Crimson Lotus",
    storyPlace: "The Sacred Ponds of Polonnaruwa",
    destinations: ["Party", "Garden"],
    colorName: "Royal Crimson",
    colorHex: "#8C1D2F",
    palette: ["#8C1D2F", "#F6F5F2", "#B86B4B"],
    fabric: "Pure Handloom Cotton Voile",
    priceAud: 280,
    image: "/images/collection-2/crimson-lotus-dress.jpg",
    imageHover: "/images/collection-2/crimson-lotus-dress-hover.jpg",
    gallery: [
      "/images/collection-2/crimson-lotus-dress.jpg",
      "/images/collection-2/crimson-lotus-dress-hover.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Rich crimson cotton voile draped in a clean square-neck bodice that unfolds into a sweeping gathered maxi skirt.",
    heritage:
      "In the ancient royal bathing pools of Polonnaruwa, sacred crimson lotuses float in still reflection beneath dramatic evening skies. Handcrafted in deeply saturated plant-inspired crimson voile, this maxi moves like liquid petals with every step, commanding effortless presence.",
    quote: "Out of stillness and quiet water, regal beauty ascends.",
    craftDetails: [
      "Sculpted square neckline with slender shoulder straps",
      "High-density micro gathers at the empire line",
      "Sweeping floor-skimming hemline with French seams",
      "Breathable natural dye finish",
    ],
    care: ["Hand wash cold separately", "Line dry in shade", "Warm iron on reverse"],
    reviews: [
      {
        id: "cl-rev-1",
        productId: "crimson-lotus-dress",
        reviewerName: "Priya Mendis",
        reviewerLocation: "Sydney, NSW",
        rating: 5,
        title: "Regal, dramatic, and unbelievably comfortable",
        body: "The crimson color is deeply saturated and romantic. Wore it to a wedding reception at dusk and felt so elegant. The fabric flows around you with every step.",
        date: "2026-08-08",
        verified: true,
        helpfulCount: 38,
        fit: "true",
        photos: ["/images/collection-2/crimson-lotus-dress.jpg"],
      },
      {
        id: "cl-rev-2",
        productId: "crimson-lotus-dress",
        reviewerName: "Siobhan T.",
        reviewerLocation: "Melbourne, VIC",
        rating: 5,
        title: "Pure artisanal poetry",
        body: "The cotton voile is so soft it feels like a second skin. The empire waist gathering creates a striking long silhouette.",
        date: "2026-07-19",
        verified: true,
        helpfulCount: 20,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "midnight-bloom-set",
    name: "The Midnight Bloom Kadupul Set",
    category: "Two Piece Sets",
    story: "The Midnight Bloom",
    storyPlace: "The Mist-Shrouded Peak Wilderness",
    destinations: ["Party", "City"],
    colorName: "Kadupul White & Onyx",
    colorHex: "#1A1A1A",
    palette: ["#1A1A1A", "#FFFFFF", "#C5A059"],
    fabric: "Artisan Crochet Lace & Cotton Voile",
    priceAud: 310,
    image: "/images/collection-2/midnight-bloom-set.jpg",
    imageHover: "/images/collection-2/midnight-bloom-set-hover.jpg",
    gallery: [
      "/images/collection-2/midnight-bloom-set.jpg",
      "/images/collection-2/midnight-bloom-set-hover.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Handcrafted white floral lace crop top paired with a dramatic midnight onyx tiered maxi skirt inspired by Sri Lanka's rare Kadupul flower.",
    heritage:
      "The Kadupul flower blooms only once a year under the darkest midnight moon, opening its celestial white petals for a few fleeting hours before dawn. This iconic two-piece unites intricate white artisanal lace with deep midnight noir tiers — poetic drama crafted for moonlit garden parties and unforgettable evenings.",
    quote: "Treasured most because it blooms only for the night.",
    craftDetails: [
      "Intricate floral lace crop top with scalloped hem",
      "Fully lined bodice for complete comfort",
      "Tiered midnight black skirt with gathered drape",
      "Versatile luxury separates",
    ],
    care: ["Hand wash lace cold, dry flat", "Machine wash skirt on cold", "Cool iron on reverse"],
    reviews: [
      {
        id: "mb-rev-1",
        productId: "midnight-bloom-set",
        reviewerName: "Elena V.",
        reviewerLocation: "Brisbane, QLD",
        rating: 5,
        title: "The crown jewel of my wardrobe",
        body: "The contrast between the delicate white floral lace crop and the voluminous midnight tiered skirt is pure drama. Photographed stunningly at an evening gala.",
        date: "2026-08-06",
        verified: true,
        helpfulCount: 42,
        fit: "true",
        photos: ["/images/collection-2/midnight-bloom-set.jpg"],
      },
      {
        id: "mb-rev-2",
        productId: "midnight-bloom-set",
        reviewerName: "Chloe M.",
        reviewerLocation: "Gold Coast, QLD",
        rating: 5,
        title: "Incredible artisan hand feel",
        body: "The lace crop has a lovely weight to it without being rigid. Truly one-of-a-kind slow fashion.",
        date: "2026-07-29",
        verified: true,
        helpfulCount: 21,
        fit: "true",
        photos: [],
      },
    ],
  },
  {
    id: "tropic-lagoon-dress",
    name: "Tropic Lagoon Gathered Maxi Dress",
    category: "Dresses",
    story: "Tropic Lagoon",
    storyPlace: "The Coral Lagoons of Hikkaduwa",
    destinations: ["Beach", "Everyday"],
    colorName: "Lagoon Aqua",
    colorHex: "#26A69A",
    palette: ["#26A69A", "#C8D8E6", "#F6F5F2"],
    fabric: "Breathable Linen-Cotton Weave",
    priceAud: 255,
    image: "/images/collection-2/tropic-lagoon-dress.jpg",
    imageHover: "/images/collection-2/tropic-lagoon-dress-hover.jpg",
    gallery: [
      "/images/collection-2/tropic-lagoon-dress.jpg",
      "/images/collection-2/tropic-lagoon-dress-hover.jpg",
      "/images/collection-2/tropic-lagoon-dress-1.jpg",
    ],
    sizes: AU_SIZES,
    description:
      "Luminous coastal aqua maxi dress featuring a structured square bodice and flowing gathered skirt. Code DR2425.",
    heritage:
      "Where coastal reef sanctuaries break the Indian Ocean swell, the waters settle into glass-calm shades of turquoise and deep lagoon aqua. Cut in an airy linen-cotton blend that naturally repels heat, this dress is made for barefoot beach strolls, seaside brunches, and tropical holidays.",
    quote: "Where ocean waves soften into tranquil, crystal pools.",
    craftDetails: [
      "Square neckline with internal stay stitching",
      "Generously gathered skirt with deep movement",
      "Functional deep side pockets",
      "Concealed back zip for clean finish",
    ],
    care: ["Cold machine wash", "Line dry in shade", "Warm iron or steam"],
    reviews: [
      {
        id: "tl-lag-rev-1",
        productId: "tropic-lagoon-dress",
        reviewerName: "Maya W.",
        reviewerLocation: "Sunshine Coast, QLD",
        rating: 5,
        title: "The color of coastal dreaming",
        body: "The aqua tone is so radiant against sunlight! And finding real, functional pockets in such a flowing maxi dress is the ultimate win.",
        date: "2026-08-03",
        verified: true,
        helpfulCount: 31,
        fit: "true",
        photos: ["/images/collection-2/tropic-lagoon-dress.jpg"],
      },
      {
        id: "tl-lag-rev-2",
        productId: "tropic-lagoon-dress",
        reviewerName: "Tahnee Miller",
        reviewerLocation: "Darwin, NT",
        rating: 5,
        title: "Pure tropical breathability",
        body: "Survived high humidity with absolute grace. Does not cling, stays cool, and washes cleanly without fading.",
        date: "2026-07-17",
        verified: true,
        helpfulCount: 19,
        fit: "true",
        photos: [],
      },
    ],
  },
];

export const CATEGORIES: (Category | "All")[] = [
  "All",
  "Dresses",
  "Tops & Blouses",
  "Skirts & Pants",
  "Two Piece Sets",
];

export interface DestinationMeta {
  key: Destination;
  label: string;
  tagline: string;
}

export const DESTINATIONS: DestinationMeta[] = [
  { key: "Beach", label: "Beach & Coast", tagline: "Airy linens, ocean blues" },
  { key: "Party", label: "Evening & Party", tagline: "Satin drape, warm glow" },
  { key: "City", label: "City & Work", tagline: "Tailored, easy structure" },
  { key: "Garden", label: "Garden & Day", tagline: "Soft florals, calm tones" },
  { key: "Everyday", label: "Everyday Ease", tagline: "Wear-anywhere staples" },
];

export function getProduct(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === slug);
}

export function getAverageRating(product: Product): number {
  if (!product.reviews || product.reviews.length === 0) return 0;
  const sum = product.reviews.reduce((acc, r) => acc + r.rating, 0);
  return sum / product.reviews.length;
}

export function getStoreReviewsAggregate(): { averageRating: number; totalReviews: number } {
  const allReviews = PRODUCTS.flatMap((p) => p.reviews || []);
  const totalReviews = allReviews.length;
  const averageRating =
    totalReviews > 0
      ? Number((allReviews.reduce((sum, r) => sum + r.rating, 0) / totalReviews).toFixed(1))
      : 4.9;
  return { averageRating, totalReviews };
}
